# -*- coding: utf-8 -*-
"""solemne3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145JOTiglqnMY-8kSBbbY5XV8Lehh0oCC
    
"""
pip install pandas
pip install matplotlib


!pip install pandas

import pandas as pd

# Reemplaza 'datos_paises_procesados.xlsx' con el nombre de tu archivo Excel
ruta_excel = "datos_paises_procesados.xlsx"

# Leer el archivo Excel
df = pd.read_excel(ruta_excel)

# Mostrar las primeras filas del DataFrame
print(df.head())

print(df.info())  # Muestra detalles del DataFrame
print(df.describe())  # Estadísticas descriptivas

# Filtrar filas donde una columna llamada "Región" sea igual a "América"
filtro = df[df["Region_geografica"] == "América"]
print(filtro)

# Crear una nueva columna con la densidad de población
df["Densidad Poblacional"] = df["Poblacion_total"] / df["Area_km²"]
print(df.head())

!pip install matplotlib

import matplotlib.pyplot as plt

# Ejemplo: Gráfico de barras de los 10 países más poblados
df_ordenado = df.sort_values(by="Poblacion_total", ascending=False).head(10)
plt.bar(df_ordenado["nombre_pais"], df_ordenado["Poblacion_total"])
plt.xticks(rotation=45)
plt.xlabel("nombre_pais")
plt.ylabel("Poblacion_total")
plt.title("Top 10 Países más Poblados")
plt.show()

df.to_excel("nuevo_archivo.xlsx", index=False)  # Guarda sin el índice
